apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-application
  namespace: prod
spec:
  project: default

  source:
    repoURL: https://github.com/filib1234/argoCDdemo.git
    targetRevision: HEAD
    path: prod

  destination:
    server: https://kubernetes.default.svc
    namespace: webapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
